### ISSUE TITLE
Gen1-TrustedLaunch: PropertyChangeNotAllowed

### ISSUE THREAD

**Issue by faizhadi906** [AjKundnani/Gen1-TrustedLaunch#2]
![Gen1-TrustedLaunch-Ghub](https://github.com/user-attachments/assets/8a0deeb9-9c32-4ec3-b315-d2da8029ad0d)

I'm getting the following errors:
Changing property 'securityProfile.securityType' is not allowed.
ErrorCode: PropertyChangeNotAllowed
ErrorMessage: Changing property 'securityProfile.securityType' is not allowed.
ErrorTarget: securityProfile.securityType
StatusCode: 409
ReasonPhrase:
OperationID : b77d6f7b-2d1a-4a2f-bdb4-2d2d1e648377
Error Caused By: Update-AzVM @paramUpdateAzVm | Out-Null

**Comment by AjKundnani** [comment]
@faizhadi906 - Please register the feature flag `Gen1ToTLMigrationPreview` using below PowerShell command and retry the operation.
``Register-AzProviderFeature -FeatureName "Gen1ToTLMigrationPreview" -ProviderNamespace "Microsoft.Compute"

Please wait for registration to complete. You can check the status of registration by running following command:
Get-AzProviderFeature -ProviderNamespace "Microsoft.Compute" -FeatureName "Gen1ToTLMigrationPreview"
