### ISSUE TITLE
MBR to GPT support validation for Windows failed. Terminating script execution.

### ISSUE THREAD

**Issue by jorgytim** [AjKundnani/Gen1-TrustedLaunch#6]
This script framework was requested by one the Microsoft Solutions Architects assigned to our business as part of a security engagement. We are looking to convert a number of VMs that were setup as Gen1 to Gen2, so we can take advantage of secure boot functionality.

I've done this against Windows server 2019 and 2016 Datacenter skus, originally deployed from Azure marketplace images. Unfortunately during this process the main "upgrade-gen1toTL.ps1" script is trying to pull a signed script from your artifacts folder, which is signed and doesn't allow me to review the content:
https://raw.githubusercontent.com/AjKundnani/Gen1-TrustedLaunch/main/artifacts/Validate-MBRToGPT.ps1

I've run this in a test tenant and our production one, and have had more than one VM fail with the following log details in my user profile (running this on a local machine in a powershell session, not cloud shell as it times out), and the output is limited to:
Shell output:
Feature Gen1ToTLMigrationPreview is already registered.
Script Version: 2.1.2
VM name = aw2rapid7-p01
Subscription ID = 53af90d0-4b0d-4af5-ae90-ea9495128866
Output Storage Account Name =
Use Cloud Shell =
Use Signed Script =
Resource group name = COR-P-INF-CYBER
Enable Secure Boot = True
Tenant Domain = sands.com
Processing VM aw2rapid7-p01 under resource group COR-P-INF-CYBER with Secure boot True
Connecting to Subscription 53af90d0-4b0d-4af5-ae90-ea9495128866 under sands.com
Mapping existing configuration for aw2rapid7-p01 under COR-P-INF-CYBER
Validating VM SKU Standard_D4s_v4 for aw2rapid7-p01 is supported for Trusted launch
VM SKU Standard_D4s_v4 supported for TLVM. Proceeding to create TLVM.
Validating MBR to GPT conversion support for aw2rapid7-p01
Write-Error: MBR to GPT support validation for Windows aw2rapid7-p01 failed. Terminating script execution.

Logfile output:
<![LOG[Script Version: 2.1.2]LOG]!><time="06:17:19.358722" date="11-14-2024" component="Setup-PreRequisites" context="" type="3" thread="" file="">
<![LOG[VM name = aw2rapid7-p01 Subscription ID = 53af90d0-4b0d-4af5-ae90-ea9495128866 Output Storage Account Name =  Use Cloud Shell =  Use Signed Script =  Resource group name = COR-P-INF-CYBER Enable Secure Boot = True Tenant Domain = sands.com]LOG]!><time="06:17:19.381554" date="11-14-2024" component="Setup-PreRequisites" context="" type="3" thread="" file="">
<![LOG[Processing VM aw2rapid7-p01 under resource group COR-P-INF-CYBER with Secure boot True]LOG]!><time="06:17:19.383312" date="11-14-2024" component="Setup-PreRequisites" context="" type="3" thread="" file="">
<![LOG[Connecting to Subscription 53af90d0-4b0d-4af5-ae90-ea9495128866 under sands.com]LOG]!><time="06:17:19.385521" date="11-14-2024" component="Connect-AzSubscription" context="" type="3" thread="" file="">
<![LOG[Mapping existing configuration for aw2rapid7-p01 under COR-P-INF-CYBER]LOG]!><time="06:17:19.550856" date="11-14-2024" component="Get-AzVM" context="" type="3" thread="" file="">
<![LOG[Validating VM SKU Standard_D4s_v4 for aw2rapid7-p01 is supported for Trusted launch]LOG]!><time="06:17:23.865546" date="11-14-2024" component="Get-AzVM" context="" type="3" thread="" file="">
<![LOG[VM SKU Standard_D4s_v4 supported for TLVM. Proceeding to create TLVM.]LOG]!><time="06:17:25.015726" date="11-14-2024" component="Get-AzVM" context="" type="3" thread="" file="">
<![LOG[Validating MBR to GPT conversion support for aw2rapid7-p01]LOG]!><time="06:17:25.017729" date="11-14-2024" component="MBR-GPT-Validation" context="" type="3" thread="" file="">
<![LOG[MBR to GPT support validation for Windows aw2rapid7-p01 failed. Terminating script execution.]LOG]!><time="06:18:26.201201" date="11-14-2024" component="MBR-GPT-Validation" context="" type="1" thread="" file="">

**Comment by AjKundnani** [comment]
Windows Server 2016 does not support MBR2GPT conversion as called out in [pre-requisites section of preview documentation](https://github.com/AjKundnani/Gen1-TrustedLaunch#pre-requisites), hence the error.

To mitigate same, please upgrade the VM to Windows Server 2019 if feasible and retry the Gen1 -> Trusted launch upgrade.
